version: '3'
tasks:
  start:
    cmds:
      - go build -o main ./cmd/ssr/
      - ./main
  migrate:
    cmds:
      - rm database.db
      - ./migrations/run.sh

  frontend:
    dir: ./frontend
    cmds:
      - npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch
